// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutonomousMove.h"

AutonomousMove::AutonomousMove(float x, float y, float z, float t) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

	m_x = x;
	m_y = y;
	m_z = z;
	SetTimeout(t);
}

// Called just before this Command runs the first time
void AutonomousMove::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void AutonomousMove::Execute() {
	Robot::driveTrain->robotDrive41->MecanumDrive_Cartesian(
			m_x,
			m_y,
			m_z,
			0); // TODO: gyro

}

// Make this return true when this Command no longer needs to run execute()
bool AutonomousMove::IsFinished() {
	return IsTimedOut();
}

// Called once after isFinished returns true
void AutonomousMove::End() {
	Robot::driveTrain->robotDrive41->MecanumDrive_Cartesian(
				0,
				0,
				0,
				0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonomousMove::Interrupted() {

}
