// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "FeederCommand.h"
#include "SetSetpoint.h"
#include "GotoSlimTote.h"
#include "GrabbersToOpen.h"
#define SECOND_TOTE_HEIGHT 13.8513
#define THIRD_TOTE_HEIGHT 32.9513
FeederCommand::FeederCommand() {
	// Add Commands here:
	// e.g. AddSequential(new Command1());
	//      AddSequential(new Command2());
	// these will run in order.
	AddSequential(new SetSetpoint(SECOND_TOTE_HEIGHT)); //Setting the elevator setpoint to the height of the second lowest tote on the stack
	AddSequential(new WaitCommand(1.0));
	AddSequential(new GrabbersToOpen()); //Open grabbers to widest position
	AddSequential(new WaitCommand(4.0));
	AddSequential (new GotoSlimTote ()); //Go to the tote facing length wise
	AddSequential(new WaitCommand(2.0));
	AddSequential (new SetSetpoint (THIRD_TOTE_HEIGHT)); //Same as above just the third tote on the stack to raise it up for another tote
	AddSequential(new WaitCommand(5.0));
	//Do we need another wait command here?

	// To run multiple commands at the same time,
	// use AddParallel()
	// e.g. AddParallel(new Command1());
	//      AddSequential(new Command2());
	// Command1 and Command2 will run in parallel.

	// A command group will require all of the subsystems that each member
	// would require.
	// e.g. if Command1 requires chassis, and Command2 requires arm,
	// a CommandGroup containing them would require both the chassis and the
	// arm.

}
