// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "MoveGrabbers.h"
#include "../OI.h"

MoveGrabbers::MoveGrabbers() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::grabbers);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void MoveGrabbers::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void MoveGrabbers::Execute() {
	
	float opStickX = Robot::oi->getDriveStickX();

	if(Robot::grabbers->grabberinsidelimit->Get() == 0 &&
		Robot::grabbers->grabberoutsidelimit->Get() == 0)
		//when the inside and outside limits are false
	{
			Robot::grabbers->grabbermotor->Set(Robot::oi->getopStick()->GetX());
			//set the motor value to the joystick value
	};

	if(Robot::grabbers->grabberinsidelimit->Get() == 1 && opStickX > 0)
		//when the inside limit is true and the joystick is moving inward
	{
		Robot::grabbers->grabbermotor->Set(0.0);
		//set motor to 0
	}
	if(Robot::grabbers->grabberoutsidelimit->Get() == 1 && opStickX < 0)
		//when the outside limit is true and the joystick is moving outward
	{
		Robot::grabbers->grabbermotor->Set(0.0);
		//set motor to 0
	}
}

// Make this return true when this Command no longer needs to run execute()
bool MoveGrabbers::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void MoveGrabbers::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void MoveGrabbers::Interrupted() {

}
