// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "SetElevatorZeroPoint.h"



SetElevatorZeroPoint::SetElevatorZeroPoint() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::elevator);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void SetElevatorZeroPoint::Initialize() {
	//TODO: change to CANTalon function
}

// Called repeatedly when this Command is scheduled to run
void SetElevatorZeroPoint::Execute(){
/*
	if(RobotMap::elevatorElevatorTalon->IsRevLimitSwitchClosed()){
		RobotMap::elevatorElevatorTalon->Set(0.0);
	}else{
		RobotMap::elevatorElevatorTalon->Set(-0.5);
	}
*/
}

// Make this return true when this Command no longer needs to run execute()
bool SetElevatorZeroPoint::IsFinished() {
//	TODO: use isLimitAlreadyHit more
//	if(RobotMap::elevatorElevatorTalon->IsRevLimitSwitchClosed()){
		return true;
//	}
//	return false;
}

// Called once after isFinished returns true
void SetElevatorZeroPoint::End() {
//	RobotMap::elevatorElevatorTalon->SetPosition(0.0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void SetElevatorZeroPoint::Interrupted() {

}
