// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"
#include "math.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDE
Robot RobotInstance;
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	drivestick = new Joystick(0);
	
	opStick = new Joystick(1);
	
     

        // SmartDashboard Buttons

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getdrivestick() {
	return drivestick;
}

Joystick* OI::getOpStick() {
	return opStick;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

//The following funcitons simply make getting the joystick axies a lot easier.
float OI::returnOpStickY(){
	return joystickDeadband(opStick->GetY());
}

float OI::returnOpStickX(){
	return joystickDeadband(opStick->GetX());
}

float OI::joystickDeadband(float joystickReturn){
	if(fabs(joystickReturn) < 0.1){
			return 0.0;
		}
		return joystickReturn;
}
